function cost = bpr_cx_cost_op(flows_op, flows_extra, graph)
% convex version of bpr.m function
% return the avg time cost to travel through each edge by the bpr function
cost = graph.Edges.freetime .* flows_op;
cost = cost + graph.Edges.freetime .* 0.15 ./ (graph.Edges.capacity.^4) .* (...
    cpower(flows_op, 5) + ...
    4.*cpower(flows_op, 4).*flows_extra + ...
    6.*cpower(flows_op,3).*(flows_extra.^2) + ...
    4.*cpower(flows_op,2).*(flows_extra.^3) + ...
    flows_op.*(flows_extra.^4));
end
